services:
  hydra-mtgsrc:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    networks:
      coolify:
        aliases:
          - hydra-mtgsrc

networks:
  coolify:
    external: true
